// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v3.12.3
// source: encounters/encounters-service.proto

package encounters

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EncounterStatus int32

const (
	EncounterStatus_Draft    EncounterStatus = 0
	EncounterStatus_Active   EncounterStatus = 1
	EncounterStatus_Archived EncounterStatus = 2
)

// Enum value maps for EncounterStatus.
var (
	EncounterStatus_name = map[int32]string{
		0: "Draft",
		1: "Active",
		2: "Archived",
	}
	EncounterStatus_value = map[string]int32{
		"Draft":    0,
		"Active":   1,
		"Archived": 2,
	}
)

func (x EncounterStatus) Enum() *EncounterStatus {
	p := new(EncounterStatus)
	*p = x
	return p
}

func (x EncounterStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EncounterStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_encounters_encounters_service_proto_enumTypes[0].Descriptor()
}

func (EncounterStatus) Type() protoreflect.EnumType {
	return &file_encounters_encounters_service_proto_enumTypes[0]
}

func (x EncounterStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EncounterStatus.Descriptor instead.
func (EncounterStatus) EnumDescriptor() ([]byte, []int) {
	return file_encounters_encounters_service_proto_rawDescGZIP(), []int{0}
}

type EncounterType int32

const (
	EncounterType_Social EncounterType = 0
	EncounterType_Hidden EncounterType = 1
	EncounterType_Misc   EncounterType = 2
)

// Enum value maps for EncounterType.
var (
	EncounterType_name = map[int32]string{
		0: "Social",
		1: "Hidden",
		2: "Misc",
	}
	EncounterType_value = map[string]int32{
		"Social": 0,
		"Hidden": 1,
		"Misc":   2,
	}
)

func (x EncounterType) Enum() *EncounterType {
	p := new(EncounterType)
	*p = x
	return p
}

func (x EncounterType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EncounterType) Descriptor() protoreflect.EnumDescriptor {
	return file_encounters_encounters_service_proto_enumTypes[1].Descriptor()
}

func (EncounterType) Type() protoreflect.EnumType {
	return &file_encounters_encounters_service_proto_enumTypes[1]
}

func (x EncounterType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EncounterType.Descriptor instead.
func (EncounterType) EnumDescriptor() ([]byte, []int) {
	return file_encounters_encounters_service_proto_rawDescGZIP(), []int{1}
}

type EmptyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *EmptyRequest) Reset() {
	*x = EmptyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_encounters_encounters_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmptyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyRequest) ProtoMessage() {}

func (x *EmptyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_encounters_encounters_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyRequest.ProtoReflect.Descriptor instead.
func (*EmptyRequest) Descriptor() ([]byte, []int) {
	return file_encounters_encounters_service_proto_rawDescGZIP(), []int{0}
}

type EmptyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *EmptyResponse) Reset() {
	*x = EmptyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_encounters_encounters_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmptyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyResponse) ProtoMessage() {}

func (x *EmptyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_encounters_encounters_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyResponse.ProtoReflect.Descriptor instead.
func (*EmptyResponse) Descriptor() ([]byte, []int) {
	return file_encounters_encounters_service_proto_rawDescGZIP(), []int{1}
}

type SocialEncountersResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SocialEncounters []*SocialEncounterResponse `protobuf:"bytes,1,rep,name=SocialEncounters,proto3" json:"SocialEncounters,omitempty"`
}

func (x *SocialEncountersResponse) Reset() {
	*x = SocialEncountersResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_encounters_encounters_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SocialEncountersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SocialEncountersResponse) ProtoMessage() {}

func (x *SocialEncountersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_encounters_encounters_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SocialEncountersResponse.ProtoReflect.Descriptor instead.
func (*SocialEncountersResponse) Descriptor() ([]byte, []int) {
	return file_encounters_encounters_service_proto_rawDescGZIP(), []int{2}
}

func (x *SocialEncountersResponse) GetSocialEncounters() []*SocialEncounterResponse {
	if x != nil {
		return x.SocialEncounters
	}
	return nil
}

type SocialEncounterResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id                   int64           `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Name                 string          `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Description          string          `protobuf:"bytes,3,opt,name=Description,proto3" json:"Description,omitempty"`
	Location             *Location       `protobuf:"bytes,4,opt,name=Location,proto3" json:"Location,omitempty"`
	Experience           int64           `protobuf:"varint,5,opt,name=Experience,proto3" json:"Experience,omitempty"`
	Status               EncounterStatus `protobuf:"varint,6,opt,name=Status,proto3,enum=encounters.EncounterStatus" json:"Status,omitempty"`
	Type                 EncounterType   `protobuf:"varint,7,opt,name=Type,proto3,enum=encounters.EncounterType" json:"Type,omitempty"`
	Radius               int64           `protobuf:"varint,8,opt,name=Radius,proto3" json:"Radius,omitempty"`
	Participants         []*Participant  `protobuf:"bytes,9,rep,name=Participants,proto3" json:"Participants,omitempty"`
	Completers           []*Completer    `protobuf:"bytes,10,rep,name=Completers,proto3" json:"Completers,omitempty"`
	RequiredParticipants int64           `protobuf:"varint,11,opt,name=RequiredParticipants,proto3" json:"RequiredParticipants,omitempty"`
	CurrentlyInRange     []*Participant  `protobuf:"bytes,12,rep,name=CurrentlyInRange,proto3" json:"CurrentlyInRange,omitempty"`
}

func (x *SocialEncounterResponse) Reset() {
	*x = SocialEncounterResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_encounters_encounters_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SocialEncounterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SocialEncounterResponse) ProtoMessage() {}

func (x *SocialEncounterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_encounters_encounters_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SocialEncounterResponse.ProtoReflect.Descriptor instead.
func (*SocialEncounterResponse) Descriptor() ([]byte, []int) {
	return file_encounters_encounters_service_proto_rawDescGZIP(), []int{3}
}

func (x *SocialEncounterResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SocialEncounterResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SocialEncounterResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *SocialEncounterResponse) GetLocation() *Location {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *SocialEncounterResponse) GetExperience() int64 {
	if x != nil {
		return x.Experience
	}
	return 0
}

func (x *SocialEncounterResponse) GetStatus() EncounterStatus {
	if x != nil {
		return x.Status
	}
	return EncounterStatus_Draft
}

func (x *SocialEncounterResponse) GetType() EncounterType {
	if x != nil {
		return x.Type
	}
	return EncounterType_Social
}

func (x *SocialEncounterResponse) GetRadius() int64 {
	if x != nil {
		return x.Radius
	}
	return 0
}

func (x *SocialEncounterResponse) GetParticipants() []*Participant {
	if x != nil {
		return x.Participants
	}
	return nil
}

func (x *SocialEncounterResponse) GetCompleters() []*Completer {
	if x != nil {
		return x.Completers
	}
	return nil
}

func (x *SocialEncounterResponse) GetRequiredParticipants() int64 {
	if x != nil {
		return x.RequiredParticipants
	}
	return 0
}

func (x *SocialEncounterResponse) GetCurrentlyInRange() []*Participant {
	if x != nil {
		return x.CurrentlyInRange
	}
	return nil
}

type Location struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        int64   `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Latitude  float32 `protobuf:"fixed32,2,opt,name=Latitude,proto3" json:"Latitude,omitempty"`
	Longitude float32 `protobuf:"fixed32,3,opt,name=Longitude,proto3" json:"Longitude,omitempty"`
}

func (x *Location) Reset() {
	*x = Location{}
	if protoimpl.UnsafeEnabled {
		mi := &file_encounters_encounters_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Location) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Location) ProtoMessage() {}

func (x *Location) ProtoReflect() protoreflect.Message {
	mi := &file_encounters_encounters_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Location.ProtoReflect.Descriptor instead.
func (*Location) Descriptor() ([]byte, []int) {
	return file_encounters_encounters_service_proto_rawDescGZIP(), []int{4}
}

func (x *Location) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Location) GetLatitude() float32 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *Location) GetLongitude() float32 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

type Participant struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          int64  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Username    string `protobuf:"bytes,2,opt,name=Username,proto3" json:"Username,omitempty"`
	EncounterId int64  `protobuf:"varint,3,opt,name=EncounterId,proto3" json:"EncounterId,omitempty"`
}

func (x *Participant) Reset() {
	*x = Participant{}
	if protoimpl.UnsafeEnabled {
		mi := &file_encounters_encounters_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Participant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Participant) ProtoMessage() {}

func (x *Participant) ProtoReflect() protoreflect.Message {
	mi := &file_encounters_encounters_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Participant.ProtoReflect.Descriptor instead.
func (*Participant) Descriptor() ([]byte, []int) {
	return file_encounters_encounters_service_proto_rawDescGZIP(), []int{5}
}

func (x *Participant) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Participant) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Participant) GetEncounterId() int64 {
	if x != nil {
		return x.EncounterId
	}
	return 0
}

type Completer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id             int64                  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Username       string                 `protobuf:"bytes,2,opt,name=Username,proto3" json:"Username,omitempty"`
	CompletionDate *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=CompletionDate,proto3" json:"CompletionDate,omitempty"`
	EncounterId    int64                  `protobuf:"varint,4,opt,name=EncounterId,proto3" json:"EncounterId,omitempty"`
}

func (x *Completer) Reset() {
	*x = Completer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_encounters_encounters_service_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Completer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Completer) ProtoMessage() {}

func (x *Completer) ProtoReflect() protoreflect.Message {
	mi := &file_encounters_encounters_service_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Completer.ProtoReflect.Descriptor instead.
func (*Completer) Descriptor() ([]byte, []int) {
	return file_encounters_encounters_service_proto_rawDescGZIP(), []int{6}
}

func (x *Completer) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Completer) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Completer) GetCompletionDate() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletionDate
	}
	return nil
}

func (x *Completer) GetEncounterId() int64 {
	if x != nil {
		return x.EncounterId
	}
	return 0
}

type ActivateSocialEncounterRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id                  string               `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	ParticipantLocation *ParticipantLocation `protobuf:"bytes,2,opt,name=ParticipantLocation,proto3" json:"ParticipantLocation,omitempty"`
}

func (x *ActivateSocialEncounterRequest) Reset() {
	*x = ActivateSocialEncounterRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_encounters_encounters_service_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ActivateSocialEncounterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivateSocialEncounterRequest) ProtoMessage() {}

func (x *ActivateSocialEncounterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_encounters_encounters_service_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivateSocialEncounterRequest.ProtoReflect.Descriptor instead.
func (*ActivateSocialEncounterRequest) Descriptor() ([]byte, []int) {
	return file_encounters_encounters_service_proto_rawDescGZIP(), []int{7}
}

func (x *ActivateSocialEncounterRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ActivateSocialEncounterRequest) GetParticipantLocation() *ParticipantLocation {
	if x != nil {
		return x.ParticipantLocation
	}
	return nil
}

type ParticipantLocation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username  string  `protobuf:"bytes,1,opt,name=Username,proto3" json:"Username,omitempty"`
	Latitude  float32 `protobuf:"fixed32,2,opt,name=Latitude,proto3" json:"Latitude,omitempty"`
	Longitude float32 `protobuf:"fixed32,3,opt,name=Longitude,proto3" json:"Longitude,omitempty"`
}

func (x *ParticipantLocation) Reset() {
	*x = ParticipantLocation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_encounters_encounters_service_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ParticipantLocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParticipantLocation) ProtoMessage() {}

func (x *ParticipantLocation) ProtoReflect() protoreflect.Message {
	mi := &file_encounters_encounters_service_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParticipantLocation.ProtoReflect.Descriptor instead.
func (*ParticipantLocation) Descriptor() ([]byte, []int) {
	return file_encounters_encounters_service_proto_rawDescGZIP(), []int{8}
}

func (x *ParticipantLocation) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *ParticipantLocation) GetLatitude() float32 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *ParticipantLocation) GetLongitude() float32 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

type SocialEncounterIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
}

func (x *SocialEncounterIdRequest) Reset() {
	*x = SocialEncounterIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_encounters_encounters_service_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SocialEncounterIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SocialEncounterIdRequest) ProtoMessage() {}

func (x *SocialEncounterIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_encounters_encounters_service_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SocialEncounterIdRequest.ProtoReflect.Descriptor instead.
func (*SocialEncounterIdRequest) Descriptor() ([]byte, []int) {
	return file_encounters_encounters_service_proto_rawDescGZIP(), []int{9}
}

func (x *SocialEncounterIdRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_encounters_encounters_service_proto protoreflect.FileDescriptor

var file_encounters_encounters_service_proto_rawDesc = []byte{
	0x0a, 0x23, 0x65, 0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x73, 0x2f, 0x65, 0x6e, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x73, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x65, 0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72,
	0x73, 0x1a, 0x1a, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x74, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x0e, 0x0a,
	0x0c, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x0f, 0x0a,
	0x0d, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x6b,
	0x0a, 0x18, 0x53, 0x6f, 0x63, 0x69, 0x61, 0x6c, 0x45, 0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65,
	0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4f, 0x0a, 0x10, 0x53, 0x6f,
	0x63, 0x69, 0x61, 0x6c, 0x45, 0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x65, 0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72,
	0x73, 0x2e, 0x53, 0x6f, 0x63, 0x69, 0x61, 0x6c, 0x45, 0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65,
	0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x10, 0x53, 0x6f, 0x63, 0x69, 0x61,
	0x6c, 0x45, 0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x73, 0x22, 0x9a, 0x04, 0x0a, 0x17,
	0x53, 0x6f, 0x63, 0x69, 0x61, 0x6c, 0x45, 0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x02, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x44,
	0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x30, 0x0a,
	0x08, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x14, 0x2e, 0x65, 0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x73, 0x2e, 0x4c, 0x6f, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x08, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x1e, 0x0a, 0x0a, 0x45, 0x78, 0x70, 0x65, 0x72, 0x69, 0x65, 0x6e, 0x63, 0x65, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x0a, 0x45, 0x78, 0x70, 0x65, 0x72, 0x69, 0x65, 0x6e, 0x63, 0x65, 0x12,
	0x33, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x1b, 0x2e, 0x65, 0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x73, 0x2e, 0x45, 0x6e, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x12, 0x2d, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x19, 0x2e, 0x65, 0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x73, 0x2e,
	0x45, 0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x61, 0x64, 0x69, 0x75, 0x73, 0x18, 0x08, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x06, 0x52, 0x61, 0x64, 0x69, 0x75, 0x73, 0x12, 0x3b, 0x0a, 0x0c, 0x50,
	0x61, 0x72, 0x74, 0x69, 0x63, 0x69, 0x70, 0x61, 0x6e, 0x74, 0x73, 0x18, 0x09, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x17, 0x2e, 0x65, 0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x73, 0x2e, 0x50,
	0x61, 0x72, 0x74, 0x69, 0x63, 0x69, 0x70, 0x61, 0x6e, 0x74, 0x52, 0x0c, 0x50, 0x61, 0x72, 0x74,
	0x69, 0x63, 0x69, 0x70, 0x61, 0x6e, 0x74, 0x73, 0x12, 0x35, 0x0a, 0x0a, 0x43, 0x6f, 0x6d, 0x70,
	0x6c, 0x65, 0x74, 0x65, 0x72, 0x73, 0x18, 0x0a, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x65,
	0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x73, 0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65,
	0x74, 0x65, 0x72, 0x52, 0x0a, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x72, 0x73, 0x12,
	0x32, 0x0a, 0x14, 0x52, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x64, 0x50, 0x61, 0x72, 0x74, 0x69,
	0x63, 0x69, 0x70, 0x61, 0x6e, 0x74, 0x73, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x03, 0x52, 0x14, 0x52,
	0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x64, 0x50, 0x61, 0x72, 0x74, 0x69, 0x63, 0x69, 0x70, 0x61,
	0x6e, 0x74, 0x73, 0x12, 0x43, 0x0a, 0x10, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x6c, 0x79,
	0x49, 0x6e, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x18, 0x0c, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e,
	0x65, 0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x73, 0x2e, 0x50, 0x61, 0x72, 0x74, 0x69,
	0x63, 0x69, 0x70, 0x61, 0x6e, 0x74, 0x52, 0x10, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x6c,
	0x79, 0x49, 0x6e, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x22, 0x54, 0x0a, 0x08, 0x4c, 0x6f, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x02, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x4c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x08, 0x4c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65,
	0x12, 0x1c, 0x0a, 0x09, 0x4c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x02, 0x52, 0x09, 0x4c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x22, 0x5b,
	0x0a, 0x0b, 0x50, 0x61, 0x72, 0x74, 0x69, 0x63, 0x69, 0x70, 0x61, 0x6e, 0x74, 0x12, 0x0e, 0x0a,
	0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x49, 0x64, 0x12, 0x1a, 0x0a,
	0x08, 0x55, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x55, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x45, 0x6e, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b,
	0x45, 0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x49, 0x64, 0x22, 0x9d, 0x01, 0x0a, 0x09,
	0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x55, 0x73, 0x65,
	0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x55, 0x73, 0x65,
	0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x42, 0x0a, 0x0e, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74,
	0x69, 0x6f, 0x6e, 0x44, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0e, 0x43, 0x6f, 0x6d, 0x70, 0x6c,
	0x65, 0x74, 0x69, 0x6f, 0x6e, 0x44, 0x61, 0x74, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x45, 0x6e, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b,
	0x45, 0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x49, 0x64, 0x22, 0x83, 0x01, 0x0a, 0x1e,
	0x41, 0x63, 0x74, 0x69, 0x76, 0x61, 0x74, 0x65, 0x53, 0x6f, 0x63, 0x69, 0x61, 0x6c, 0x45, 0x6e,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e,
	0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x64, 0x12, 0x51,
	0x0a, 0x13, 0x50, 0x61, 0x72, 0x74, 0x69, 0x63, 0x69, 0x70, 0x61, 0x6e, 0x74, 0x4c, 0x6f, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x65, 0x6e,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x73, 0x2e, 0x50, 0x61, 0x72, 0x74, 0x69, 0x63, 0x69,
	0x70, 0x61, 0x6e, 0x74, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x13, 0x50, 0x61,
	0x72, 0x74, 0x69, 0x63, 0x69, 0x70, 0x61, 0x6e, 0x74, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x22, 0x6b, 0x0a, 0x13, 0x50, 0x61, 0x72, 0x74, 0x69, 0x63, 0x69, 0x70, 0x61, 0x6e, 0x74,
	0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x55, 0x73, 0x65, 0x72,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x55, 0x73, 0x65, 0x72,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x4c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x08, 0x4c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65,
	0x12, 0x1c, 0x0a, 0x09, 0x4c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x02, 0x52, 0x09, 0x4c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x22, 0x2a,
	0x0a, 0x18, 0x53, 0x6f, 0x63, 0x69, 0x61, 0x6c, 0x45, 0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65,
	0x72, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x64, 0x2a, 0x36, 0x0a, 0x0f, 0x45, 0x6e,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x09, 0x0a,
	0x05, 0x44, 0x72, 0x61, 0x66, 0x74, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x41, 0x63, 0x74, 0x69,
	0x76, 0x65, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x41, 0x72, 0x63, 0x68, 0x69, 0x76, 0x65, 0x64,
	0x10, 0x02, 0x2a, 0x31, 0x0a, 0x0d, 0x45, 0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x0a, 0x0a, 0x06, 0x53, 0x6f, 0x63, 0x69, 0x61, 0x6c, 0x10, 0x00, 0x12,
	0x0a, 0x0a, 0x06, 0x48, 0x69, 0x64, 0x64, 0x65, 0x6e, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x4d,
	0x69, 0x73, 0x63, 0x10, 0x02, 0x32, 0xb6, 0x02, 0x0a, 0x11, 0x45, 0x6e, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x65, 0x72, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x5a, 0x0a, 0x16, 0x47,
	0x65, 0x74, 0x41, 0x6c, 0x6c, 0x53, 0x6f, 0x63, 0x69, 0x61, 0x6c, 0x45, 0x6e, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x65, 0x72, 0x73, 0x12, 0x18, 0x2e, 0x65, 0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65,
	0x72, 0x73, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x24, 0x2e, 0x65, 0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x73, 0x2e, 0x53, 0x6f, 0x63,
	0x69, 0x61, 0x6c, 0x45, 0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x61, 0x0a, 0x13, 0x50, 0x6f, 0x73, 0x74, 0x53,
	0x6f, 0x63, 0x69, 0x61, 0x6c, 0x45, 0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x12, 0x23,
	0x2e, 0x65, 0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x73, 0x2e, 0x53, 0x6f, 0x63, 0x69,
	0x61, 0x6c, 0x45, 0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x1a, 0x23, 0x2e, 0x65, 0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x73,
	0x2e, 0x53, 0x6f, 0x63, 0x69, 0x61, 0x6c, 0x45, 0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x62, 0x0a, 0x17, 0x41, 0x63,
	0x74, 0x69, 0x76, 0x61, 0x74, 0x65, 0x53, 0x6f, 0x63, 0x69, 0x61, 0x6c, 0x45, 0x6e, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x65, 0x72, 0x12, 0x2a, 0x2e, 0x65, 0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65,
	0x72, 0x73, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x76, 0x61, 0x74, 0x65, 0x53, 0x6f, 0x63, 0x69, 0x61,
	0x6c, 0x45, 0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x19, 0x2e, 0x65, 0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x73, 0x2e, 0x45,
	0x6d, 0x70, 0x74, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x1d,
	0x5a, 0x1b, 0x65, 0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x73, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2f, 0x65, 0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x73, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_encounters_encounters_service_proto_rawDescOnce sync.Once
	file_encounters_encounters_service_proto_rawDescData = file_encounters_encounters_service_proto_rawDesc
)

func file_encounters_encounters_service_proto_rawDescGZIP() []byte {
	file_encounters_encounters_service_proto_rawDescOnce.Do(func() {
		file_encounters_encounters_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_encounters_encounters_service_proto_rawDescData)
	})
	return file_encounters_encounters_service_proto_rawDescData
}

var file_encounters_encounters_service_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_encounters_encounters_service_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_encounters_encounters_service_proto_goTypes = []interface{}{
	(EncounterStatus)(0),                   // 0: encounters.EncounterStatus
	(EncounterType)(0),                     // 1: encounters.EncounterType
	(*EmptyRequest)(nil),                   // 2: encounters.EmptyRequest
	(*EmptyResponse)(nil),                  // 3: encounters.EmptyResponse
	(*SocialEncountersResponse)(nil),       // 4: encounters.SocialEncountersResponse
	(*SocialEncounterResponse)(nil),        // 5: encounters.SocialEncounterResponse
	(*Location)(nil),                       // 6: encounters.Location
	(*Participant)(nil),                    // 7: encounters.Participant
	(*Completer)(nil),                      // 8: encounters.Completer
	(*ActivateSocialEncounterRequest)(nil), // 9: encounters.ActivateSocialEncounterRequest
	(*ParticipantLocation)(nil),            // 10: encounters.ParticipantLocation
	(*SocialEncounterIdRequest)(nil),       // 11: encounters.SocialEncounterIdRequest
	(*timestamppb.Timestamp)(nil),          // 12: google.protobuf.Timestamp
}
var file_encounters_encounters_service_proto_depIdxs = []int32{
	5,  // 0: encounters.SocialEncountersResponse.SocialEncounters:type_name -> encounters.SocialEncounterResponse
	6,  // 1: encounters.SocialEncounterResponse.Location:type_name -> encounters.Location
	0,  // 2: encounters.SocialEncounterResponse.Status:type_name -> encounters.EncounterStatus
	1,  // 3: encounters.SocialEncounterResponse.Type:type_name -> encounters.EncounterType
	7,  // 4: encounters.SocialEncounterResponse.Participants:type_name -> encounters.Participant
	8,  // 5: encounters.SocialEncounterResponse.Completers:type_name -> encounters.Completer
	7,  // 6: encounters.SocialEncounterResponse.CurrentlyInRange:type_name -> encounters.Participant
	12, // 7: encounters.Completer.CompletionDate:type_name -> google.protobuf.Timestamp
	10, // 8: encounters.ActivateSocialEncounterRequest.ParticipantLocation:type_name -> encounters.ParticipantLocation
	2,  // 9: encounters.EncountersService.GetAllSocialEncounters:input_type -> encounters.EmptyRequest
	5,  // 10: encounters.EncountersService.PostSocialEncounter:input_type -> encounters.SocialEncounterResponse
	9,  // 11: encounters.EncountersService.ActivateSocialEncounter:input_type -> encounters.ActivateSocialEncounterRequest
	4,  // 12: encounters.EncountersService.GetAllSocialEncounters:output_type -> encounters.SocialEncountersResponse
	5,  // 13: encounters.EncountersService.PostSocialEncounter:output_type -> encounters.SocialEncounterResponse
	3,  // 14: encounters.EncountersService.ActivateSocialEncounter:output_type -> encounters.EmptyResponse
	12, // [12:15] is the sub-list for method output_type
	9,  // [9:12] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_encounters_encounters_service_proto_init() }
func file_encounters_encounters_service_proto_init() {
	if File_encounters_encounters_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_encounters_encounters_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmptyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_encounters_encounters_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmptyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_encounters_encounters_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SocialEncountersResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_encounters_encounters_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SocialEncounterResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_encounters_encounters_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Location); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_encounters_encounters_service_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Participant); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_encounters_encounters_service_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Completer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_encounters_encounters_service_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ActivateSocialEncounterRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_encounters_encounters_service_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ParticipantLocation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_encounters_encounters_service_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SocialEncounterIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_encounters_encounters_service_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_encounters_encounters_service_proto_goTypes,
		DependencyIndexes: file_encounters_encounters_service_proto_depIdxs,
		EnumInfos:         file_encounters_encounters_service_proto_enumTypes,
		MessageInfos:      file_encounters_encounters_service_proto_msgTypes,
	}.Build()
	File_encounters_encounters_service_proto = out.File
	file_encounters_encounters_service_proto_rawDesc = nil
	file_encounters_encounters_service_proto_goTypes = nil
	file_encounters_encounters_service_proto_depIdxs = nil
}
